dist: trusty
sudo: false

language: c

git:
  depth: 1

compiler:
  - gcc
  - clang

env:
  matrix:
    - RE2C_VERSION="0.13.6"
    - RE2C_VERSION="1.0.3"

os:
  - linux
  - osx

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.local/opt/re2c
    - $HOME/.cache/re2c

addons:
  apt:
    packages:
      libjson-c-dev

install:
  - sh tests/install-re2c $RE2C_VERSION
  - sh autogen.sh

before_script:
  - ./configure --enable-debug

script:
  - make
