dist: trusty
sudo: false

language: c

git:
  depth: 1

compiler:
  - gcc
  - clang

env:
  global:
    - RE2C_VERSION=1.0.3
  matrix:
    - CC=gcc
    - CC=clang

matrix:
  fast_finish: true
  exclude:
    - env: CC=gcc
      compiler: clang
    - env: CC=clang
      compiler: gcc
  include:
    - env: CC=gcc RE2C_VERSION=0.13.6
      compiler: gcc
    - env: CC=clang RE2C_VERSION=0.13.6
      compiler: clang

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.local/opt/re2c
    - $HOME/.cache/re2c
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    update: true
    packages:
      check
      libjson-c-dev

before_install:
  - $CC --version

install:
  - sh tests/install-re2c $RE2C_VERSION
  - sh autogen.sh

script:
  - ./configure --enable-debug --enable-gcov --enable-unit-test
  - make
  - make check

after_success:
  - if [[ ! -z "${CODECOV_TOKEN}" ]]; then (bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"); fi;

after_failure:
  - cat tests/tests-suite.log

notifications:
  email:
    on_success: never
    on_failure: never
