dist: trusty
sudo: false

language: c

git:
  depth: 1

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - re2c

os:
  - linux
  - osx

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make
